// Generated by scripts/generate-brand.mjs — run `npm run brand` to update.
//
// The rising sun over its horizon rule, on a 512-unit grid. Drawn inline by
// <BrandMark> so the masthead tile matches public/logo.svg exactly.
export const MARK_GRID = 512
export const MARK_RADIUS = 96
export const MARK_SUN =
  'M122.88 325.12A133.12 133.12 0 0 1 389.12 325.12ZM103.17 247.25L60.71 235.09L54.25 250.69L92.87 272.12ZM172.19 175.47L143.64 141.77L129.6 151.15L149.81 190.42ZM269.46 154.13L264.44 110.25L247.56 110.25L242.54 154.13ZM362.19 190.42L382.4 151.15L368.36 141.77L339.81 175.47ZM419.13 272.12L457.75 250.69L451.29 235.09L408.83 247.25Z'
export const MARK_HORIZON = {
  x: 71.68,
  y: 325.12,
  width: 368.64,
  height: 15.36,
}
