// Generated by scripts/generate-brand.mjs — run `npm run brand` to update.
//
// The red medallion: white rising sun, horizon rule and thin ring on a
// 512-unit grid. Drawn inline by <BrandMark> so the masthead medallion
// matches public/logo.svg exactly.
export const MARK_GRID = 512
export const MARK_RING = {
  r: 217.6,
  stroke: 13.31,
}
export const MARK_SUN =
  'M153.6 299.52A102.4 102.4 0 0 1 358.4 299.52ZM133.38 235.69L81.99 218.38L75.58 233.85L124.16 257.95ZM189.51 178.32L156.4 135.38L142.47 144.68L169.47 191.71ZM268.05 161.81L264.37 107.7L247.63 107.7L243.95 161.81ZM342.53 191.71L369.53 144.68L355.6 135.38L322.49 178.32ZM387.84 257.95L436.42 233.85L430.01 218.38L378.62 235.69Z'
export const MARK_HORIZON = {
  x: 69.12,
  y: 299.52,
  width: 373.76,
  height: 13.82,
}
